# Generated by Django 2.2.28 on 2023-10-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_horoscope'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Horoscope',
        ),
    ]
