# Generated by Django 2.2.28 on 2023-10-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20231011_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='total',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
